---
application:
  name: "fixer-io-request"
  project: "fixer-io-request"
  organization: "QoveryCommunity"
routers:
- name: "main-fixer-io-request"
  routes:
  - application_name: "fixer-io-request"
    paths:
    - "/*"
